version: "3.8"
services:
  db:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: springtech
      POSTGRES_PASSWORD: springtech
      POSTGRES_DB: job
    ports:
      - "5432:5432"
#    command: ["postgres", "-h", "localhost", "-p", "5432", "--create-db", "job", "--create-db", "company", "--create-db", "review"]
    restart: always


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: springtech@gmail.com
      PGADMIN_DEFAULT_PASSWORD: springtech
#      PGADMIN_CONFIG_SERVER_MODE: false
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  service-registry:
    container_name: service-registry
    image: service-registry:latest
    ports:
      - "8761:8761"
    depends_on:
      - db
      - pgadmin
      - zipkin
      - rabbitmq

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE = docker

  config-server:
    container_name: config-server
    image: config-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE = docker

  company-ms:
    container_name: company-ms
    image: company-ms:latest
    restart: always
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE = docker


  job-ms:
    container_name: job-ms
    image: job-ms:latest
    restart: always
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE = docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE = http://service-registry:8761/eureka

  review-ms:
    container_name: review-ms
    image: review-ms:latest
    restart: always
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE = docker

